name: cine_echo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  marquee: ^2.1.0
  url_launcher: ^6.3.2
  flutter_secure_storage: ^9.0.0
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  google_sign_in: ^6.2.2
  provider: ^6.1.5+1
  flutter_carousel_widget: ^3.1.0
  envied: ^1.3.2
  http: ^1.6.0
  redacted: ^1.0.13
  heroicons: ^0.9.0
  connectivity_plus: ^5.0.0
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  envied_generator: ^1.3.2
  build_runner: ^2.10.5

flutter:
  uses-material-design: true
  assets:
    - assets/splash/
    - assets/images/

